### ISSUE TITLE
workshop/review the contributions survey!

### ISSUE THREAD

**Issue by DanM3rcurius** [SecretDecks/Catalyst-Proposals#2]
@DanM3rcurius commented on [Thu Jun 24 2021](https://github.com/SecretDecks/Documentation/issues/56)

@DanM3rcurius , @evolayak - I suggest we workshop/review the contributions survey to completely revise it to our needs. A lot of the categories were included for NFT-DAO. We could do this as a meeting or just share a markdown version on GitHub and revise from there ?

_Originally posted by @stephen-rowan in https://github.com/SecretDecks/Documentation/issues/44#issuecomment-860595662_

---

@stephen-rowan commented on [Fri Jun 25 2021](https://github.com/SecretDecks/Documentation/issues/56#issuecomment-868025035)

Reply to https://github.com/SecretDecks/Documentation/issues/56#issue-929020016

There is already a markdown version here we can revise https://github.com/SecretDecks/Documentation/blob/main/surveys/contribution/template-contribution-survey.md

---

@DanM3rcurius commented on [Wed Oct 20 2021](https://github.com/SecretDecks/Documentation/issues/56#issuecomment-947441354)

closing this, work continues in #119

**Comment by evolayak** [comment]
I’d really like a meeting to be honest. Just so I learn more and get a good idea of how to structure something like this, things to consider and whatnot. Im really interested in this sort of stuff. :D

**Comment by DanM3rcurius** [comment]
At this stage we're on the same skill level. Never got into YAML seriously, most likely will happen over the holidays.

**Comment by DanM3rcurius** [comment]
YAML is created, survey development will continue in a separate task
